@startuml AssetBoard in Library page
hide empty members
hide private members
remove @unlinked

!include Types/Asset.puml
!include Components/AssetBoard/Board.puml
!include Components/AssetBoard/Card.puml
!include Components/AssetBoard/AddButton.puml
!include Util/apiUtil.puml
!include Store/UserAccess.puml
!include Util/envUtil.puml

Board ..> apiUtil : <<uses>>
Board "1" *-- "0..*" Card
Card *-- AddButton
apiUtil ..> UserAccess : <<uses>>
apiUtil ..> envUtil_API : <<uses>>

apiUtil -r[hidden]- Card
Asset -r[hidden]- Board
Asset -d[hidden]- apiUtil
note top of Card : Displays a \nsingle asset
@enduml