@startuml
hide empty members
hide private members
remove @unlinked

!include Types/Asset.puml
!include Components/AssetBoard/AddButton.puml
!include Components/AssetBoard/Card.puml
!include Components/AssetBoard/Info.puml

class "Structual::PopUp" as PopUp {
    + title: string
    + PrimaryButton: ReactElement
    + SecondaryButton: ReactElement
    + content?: string
    + Close()
}


Card *-- AddButton
Card *-- Info
Info o-l- AddButton
Info -u-|> PopUp


AddButton -u[hidden]- Asset
@enduml