@startuml Library page composition in class diagram 
hide empty members
hide private members

!include Types/Asset.puml
!include Components/AssetBoard/Board.puml
!include Components/ShoppingCart/ShoppingCart.puml
!include Util/apiUtil.puml
!include Store/CartAccess.puml

class "Route::Library" as LibraryRoute
class "Page::Structual::Tabs" as Tabs

class Board #LightBlue
class Shop #LightBlue
class apiUtil #LightBlue

LibraryRoute o-- Shop
LibraryRoute o-r- Tabs
Tabs "1" *-- "5 " Board
Board ..> apiUtil : <<uses>>
Board ..> CartAccess : <<uses>>
Shop ..> CartAccess : <<uses>>


'note left of CartAccess : Gives acces to the \ncurrently selected \nassets
@enduml