@startuml Library Shopping cart diagram
hide empty members

!include Types/Asset.puml
!include Components/ShoppingCart/ShoppingCart.puml
!include Components/ShoppingCart/List.puml
!include Store/CartAccess.puml

class Shop #LightBlue
class List #LightBlue

Shop *-- List
Shop ..> CartAccess : <<uses>>
List .r.> CartAccess : <<uses>>
@enduml