@startuml API utility on Library page
hide empty members
hide private members
remove @unlinked

!include Types/Asset.puml
!include Components/AssetBoard/Board.puml
!include Util/apiUtil.puml
!include Store/UserAccess.puml
!include Util/envUtil.puml

class RelayEnvironment
RelayEnvironment ..> envUtil_API : <<uses>>
Board ..> apiUtil : <<uses>>
apiUtil .r.> RelayEnvironment : <<uses>>
apiUtil ..> UserAccess : <<uses>>
apiUtil ..> envUtil_API : <<uses>>
@enduml