@startuml
hide empty members
remove @unlinked

!include Types/KeyLinkPair.puml
!include Store/UserAccess.puml
!include Util/envUtil.puml
!include Components/LinkButtons.puml
!include Components/LinkButtonsLib.puml

class "Route::Workbench" as Workbench {
}

Workbench ..> envUtil_Workbench: <<uses>>
envUtil_Workbench ..> UserAccess: <<uses>>
Workbench o-- LinkButtons
LinkButtons ..> LinkButtonsLib: <<imports>>
@enduml