#!/usr/bin/env sh

if git diff --name-only origin...HEAD | grep "^client/" >/dev/null; then
    cd client
    yarn install
    yarn jest . --coverage=false
else
    echo "No changes in the client directory. Skipping pre-push hook."
fi
