#!/usr/bin/env sh

if git diff --cached --name-only | grep "^client/" >/dev/null; then
    cd client
    yarn install
    yarn format && yarn syntax
else
    echo "No changes in the client directory. Skipping pre-commit hook."
fi
