---
version: "2"
plugins:
  shellcheck:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        - typescript:
        - javascript:
        - python:
        - php:
  eslint:
    enabled: true
    config:
      config: .eslintrc
  fixme:
    enabled: true
exclude_patterns:
  - "**.md"
  - "**.txt"
  - "**.json"
  - docs/
